apiVersion: v1
kind: Secret
metadata:
  name: vault-approle-credentials
  namespace: cert-vault-demo
type: Opaque
stringData:
  roleId: "bbdfc669-5cbc-bb82-4adc-6ab590e82425" # replace with your actual roleId
  secretId: "ffac38ad-027b-58f3-c6c1-5d8d987ac1bb" # replace with your actual secretId
