FROM gcr.io/istio-testing/build-tools:master-bec02d1500de2bedfda86c3093d3be4ce8be2656

RUN wget https://github.com/tinygo-org/tinygo/releases/download/v0.30.0/tinygo_0.30.0_amd64.deb && \
    sudo dpkg -i tinygo_0.30.0_amd64.deb