apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: otel-telemetry
spec:
  gatewayClassName: eg
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: otel-telemetry
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: otel-telemetry
spec:
  telemetry:
    tracing:
      provider:
        backendRefs:
          - name: otel-collector
            namespace: monitoring
            port: 4317
      tags:
        "k8s.cluster.name": "envoy-gateway"
        "k8s.pod.name": "%ENVIRONMENT(ENVOY_POD_NAME)%"
        "k8s.namespace.name": "%ENVIRONMENT(ENVOY_POD_NAMESPACE)%"
    # metrics:
    #   prometheus: {}
    #   sinks:
    #     - type: OpenTelemetry
    #       openTelemetry:
    #         backendRefs:
    #           - name: otel-collector
    #             namespace: monitoring
    #             port: 4317
    # accessLog:
    #   settings:
    #     - format:
    #         type: Text
    #         text: |
    #           [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%"
    #       sinks:
    #         - type: File
    #           file:
    #             path: /dev/stdout
    #         - type: OpenTelemetry
    #           openTelemetry:
    #             backendRefs:
    #             - name: otel-collector
    #               namespace: monitoring
    #               port: 4317
    #             resources:
    #               k8s.cluster.name: "envoy-gateway"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: otel-telemetry
spec:
  parentRefs:
    - name: otel-telemetry
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /otel
      filters:
        - type: URLRewrite
          urlRewrite:
            hostname: www.httpbin.org
            path:
              type: ReplaceFullPath
              replaceFullPath: /headers
      backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: httpbin
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: httpbin
spec:
  endpoints:
    - fqdn:
        hostname: "www.httpbin.org"
        port: 80
