---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gtw1
spec:
  gatewayClassName: eg
  listeners:
    - name: http
      protocol: HTTP
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gtw2
spec:
  gatewayClassName: eg
  listeners:
    - name: http
      protocol: HTTP
      port: 80
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyPatchPolicy
metadata:
  name: multiple-targetrefs
spec:
  jsonPatches:
    - name: "default/gtw1/http"
      operation:
        op: add
        path: /default_filter_chain/filters/0/typed_config/http_filters/0
        value:
          name: "envoy.lua"
          typedConfig:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            typeUrl: type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
            value:
              inline_code: |
                function envoy_on_request(request_handle)
                  -- Make an HTTP call to an upstream host with the following headers, body, and timeout.
                  val = request_handle:headers():get("x-envoy-peer-metadata-id")
                  request_handle:logWarn("get result: " .. val)
                end
      type: type.googleapis.com/envoy.config.listener.v3.Listener
    - name: "default/gtw2/http"
      operation:
        op: add
        path: /default_filter_chain/filters/0/typed_config/http_filters/0
        value:
          name: "envoy.lua"
          typedConfig:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            typeUrl: type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
            value:
              inline_code: |
                function envoy_on_request(request_handle)
                  -- Make an HTTP call to an upstream host with the following headers, body, and timeout.
                  val = request_handle:headers():get("x-envoy-peer-metadata-id")
                  request_handle:logWarn("get result: " .. val)
                end
      type: type.googleapis.com/envoy.config.listener.v3.Listener
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gtw1
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gtw2
  type: JSONPatch