# kubectl label ns istio-system istio-discovery=enabled --overwrite
# kubectl label ns sidecar istio-discovery=enabled --overwrite
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: minimal
  revision: green
  meshConfig:
    accessLogFile: /dev/stdout
  values:
    gateways:
      istio-ingressgateway:
        injectionTemplate: gateway
    global:
      meshID: mesh1
      multiCluster:
        clusterName: primary
      network: network1
